// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxsrxdlsnabpshncdplv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54c3J4ZGxzbmFicHNobmNkcGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTE1NDcsImV4cCI6MjA2NTQ4NzU0N30.ZqVwsMeCHTpr5_CH_lQ9Gs5fNTKO5Y9VpOuSBL3nsg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);